name: Deploy to Google Cloud Storage

on:
  push:
    paths:
      - "data/json/**"
    branches:
      - staging
  workflow_dispatch:

env:
  JSON_DIR: data/json/
  GCR_REPO_NAME: "gcp-test"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_KEY }}

      - name: Setup Artifact Registry
        run: |
          gcloud config set artifacts/repository $GCR_REPO_NAME
