name: Deploy to Google Cloud Storage

on:
  push:
    paths:
      - "data/json/**"
    branches:
      - staging
  workflow_dispatch:

env:
  # 環境変数
  JSON_DIR: data/json/

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_KEY }}
